### Spin-0 probabilities from JHUGen ###
RecoProbabilities_SpinZero_JHUGen = [
   ## Decay probabilities #
   "Name:GG_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:ZZGG MatrixElement:JHUGen",

   "Name:GG_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_ghz2_1_JHUGen Process:H0hplus Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_ghz4_1_JHUGen Process:H0minus Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_gha2_1_JHUGen Process:H0_gsgs Production:ZZGG MatrixElement:JHUGen",
   "Name:GG_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:ZZGG MatrixElement:JHUGen",

   "Name:GG_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz1_prime2=1,0",
   #"Name:GG_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz1_prime2=0,1",
   "Name:GG_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz2=1,0",
   "Name:GG_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz2=0,1",
   "Name:GG_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz4=1,0",
   "Name:GG_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghz4=0,1",

   "Name:GG_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs1_prime2=1,0",
   "Name:GG_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs1_prime2=0,1",
   "Name:GG_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs2=1,0",
   #"Name:GG_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs2=0,1",
   "Name:GG_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs4=1,0",
   #"Name:GG_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghzgs4=0,1",

   "Name:GG_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghgsgs2=1,0",
   #"Name:GG_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghgsgs2=0,1",
   "Name:GG_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghgsgs4=1,0",
   #"Name:GG_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:ZZGG MatrixElement:JHUGen Couplings:ghg2=1,0;ghz1=1,0;ghgsgs4=0,1",

   ## Production probabilities ##
   # JJVBF/JVBF
   "Name:JJVBF_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_JHUGen_JECUp Process:HSMHiggs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_JHUGen_JECDn Process:HSMHiggs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",

   "Name:JJVBF_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz1prime2_1_JHUGen_JECUp Process:H0_g1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz1prime2_1_JHUGen_JECDn Process:H0_g1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz2_1_JHUGen Process:H0hplus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz2_1_JHUGen_JECUp Process:H0hplus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz2_1_JHUGen_JECDn Process:H0hplus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz4_1_JHUGen Process:H0minus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz4_1_JHUGen_JECUp Process:H0minus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghz4_1_JHUGen_JECDn Process:H0minus Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza1prime2_1_JHUGen_JECUp Process:H0_Zgsg1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza1prime2_1_JHUGen_JECDn Process:H0_Zgsg1prime2 Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza2_1_JHUGen_JECUp Process:H0_Zgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza2_1_JHUGen_JECDn Process:H0_Zgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza4_1_JHUGen_JECUp Process:H0_Zgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_ghza4_1_JHUGen_JECDn Process:H0_Zgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha2_1_JHUGen Process:H0_gsgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha2_1_JHUGen_JECUp Process:H0_gsgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha2_1_JHUGen_JECDn Process:H0_gsgs Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha4_1_JHUGen_JECUp Process:H0_gsgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",
   "Name:JJVBF_SIG_gha4_1_JHUGen_JECDn Process:H0_gsgs_PS Production:JJVBF MatrixElement:JHUGen Options:AddPAux",

   "Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghz4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1 Options:AddPAux",

   "Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_ghza4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1 Options:AddPAux",

   "Name:JJVBF_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_gha2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_gha2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_gha4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0 Options:AddPAux",
   "Name:JJVBF_SIG_ghz1_1_gha4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1 Options:AddPAux",
   #"Name:JJVBF_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1 Options:AddPAux",

   # JJQCD
   "Name:JJQCD_SIG_ghg2_1_JHUGen Process:HSMHiggs Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg2_1_JHUGen_JECUp Process:HSMHiggs Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg2_1_JHUGen_JECDn Process:HSMHiggs Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg4_1_JHUGen Process:H0minus Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg4_1_JHUGen_JECUp Process:H0minus Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg4_1_JHUGen_JECDn Process:H0minus Production:JJQCD MatrixElement:JHUGen",
   "Name:JJQCD_SIG_ghg2_1_ghg4_1_JHUGen Process:SelfDefine_spin0 Production:JJQCD MatrixElement:JHUGen Couplings:ghg2=1,0;ghg4=1,0",
   "Name:JJQCD_SIG_ghg2_1_ghg4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:JJQCD MatrixElement:JHUGen Couplings:ghg2=1,0;ghg4=1,0",
   "Name:JJQCD_SIG_ghg2_1_ghg4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:JJQCD MatrixElement:JHUGen Couplings:ghg2=1,0;ghg4=1,0",

   # Hadronic ZH
   "Name:HadZH_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz1_1_JHUGen_JECUp Process:HSMHiggs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz1_1_JHUGen_JECDn Process:HSMHiggs Production:Had_ZH MatrixElement:JHUGen",

   "Name:HadZH_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz1prime2_1_JHUGen_JECUp Process:H0_g1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz1prime2_1_JHUGen_JECDn Process:H0_g1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz2_1_JHUGen Process:H0hplus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz2_1_JHUGen_JECUp Process:H0hplus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz2_1_JHUGen_JECDn Process:H0hplus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz4_1_JHUGen Process:H0minus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz4_1_JHUGen_JECUp Process:H0minus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghz4_1_JHUGen_JECDn Process:H0minus Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza1prime2_1_JHUGen_JECUp Process:H0_Zgsg1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza1prime2_1_JHUGen_JECDn Process:H0_Zgsg1prime2 Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza2_1_JHUGen_JECUp Process:H0_Zgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza2_1_JHUGen_JECDn Process:H0_Zgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza4_1_JHUGen_JECUp Process:H0_Zgs_PS Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_ghza4_1_JHUGen_JECDn Process:H0_Zgs_PS Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha2_1_JHUGen Process:H0_gsgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha2_1_JHUGen_JECUp Process:H0_gsgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha2_1_JHUGen_JECDn Process:H0_gsgs Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha4_1_JHUGen_JECUp Process:H0_gsgs_PS Production:Had_ZH MatrixElement:JHUGen",
   "Name:HadZH_SIG_gha4_1_JHUGen_JECDn Process:H0_gsgs_PS Production:Had_ZH MatrixElement:JHUGen",

   "Name:HadZH_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   "Name:HadZH_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   "Name:HadZH_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   "Name:HadZH_SIG_ghz1_1_ghz4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",

   "Name:HadZH_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   "Name:HadZH_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   "Name:HadZH_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   "Name:HadZH_SIG_ghz1_1_ghza4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   #"Name:HadZH_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",
   #"Name:HadZH_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",

   "Name:HadZH_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   "Name:HadZH_SIG_ghz1_1_gha2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   "Name:HadZH_SIG_ghz1_1_gha2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   #"Name:HadZH_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   #"Name:HadZH_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   #"Name:HadZH_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   "Name:HadZH_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   "Name:HadZH_SIG_ghz1_1_gha4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   "Name:HadZH_SIG_ghz1_1_gha4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   #"Name:HadZH_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
   #"Name:HadZH_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
   #"Name:HadZH_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",

   # Hadronic WH
   "Name:HadWH_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz1_1_JHUGen_JECUp Process:HSMHiggs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz1_1_JHUGen_JECDn Process:HSMHiggs Production:Had_WH MatrixElement:JHUGen",

   "Name:HadWH_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz1prime2_1_JHUGen_JECUp Process:H0_g1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz1prime2_1_JHUGen_JECDn Process:H0_g1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz2_1_JHUGen Process:H0hplus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz2_1_JHUGen_JECUp Process:H0hplus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz2_1_JHUGen_JECDn Process:H0hplus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz4_1_JHUGen Process:H0minus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz4_1_JHUGen_JECUp Process:H0minus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghz4_1_JHUGen_JECDn Process:H0minus Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza1prime2_1_JHUGen_JECUp Process:H0_Zgsg1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza1prime2_1_JHUGen_JECDn Process:H0_Zgsg1prime2 Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza2_1_JHUGen_JECUp Process:H0_Zgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza2_1_JHUGen_JECDn Process:H0_Zgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza4_1_JHUGen_JECUp Process:H0_Zgs_PS Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_ghza4_1_JHUGen_JECDn Process:H0_Zgs_PS Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha2_1_JHUGen Process:H0_gsgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha2_1_JHUGen_JECUp Process:H0_gsgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha2_1_JHUGen_JECDn Process:H0_gsgs Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha4_1_JHUGen_JECUp Process:H0_gsgs_PS Production:Had_WH MatrixElement:JHUGen",
   "Name:HadWH_SIG_gha4_1_JHUGen_JECDn Process:H0_gsgs_PS Production:Had_WH MatrixElement:JHUGen",

   "Name:HadWH_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   "Name:HadWH_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   "Name:HadWH_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   "Name:HadWH_SIG_ghz1_1_ghz4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghz4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",

   "Name:HadWH_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza1prime2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   "Name:HadWH_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   "Name:HadWH_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   "Name:HadWH_SIG_ghz1_1_ghza4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   #"Name:HadWH_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",
   #"Name:HadWH_SIG_ghz1_1_ghza4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",

   "Name:HadWH_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   "Name:HadWH_SIG_ghz1_1_gha2_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   "Name:HadWH_SIG_ghz1_1_gha2_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   #"Name:HadWH_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   #"Name:HadWH_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   #"Name:HadWH_SIG_ghz1_1_gha2_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   "Name:HadWH_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   "Name:HadWH_SIG_ghz1_1_gha4_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   "Name:HadWH_SIG_ghz1_1_gha4_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   #"Name:HadWH_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
   #"Name:HadWH_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECUp Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
   #"Name:HadWH_SIG_ghz1_1_gha4_1_pi2_JHUGen_JECDn Process:SelfDefine_spin0 Production:Had_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",

   # JQCD
   "Name:JQCD_SIG_ghg2_1_JHUGen Process:HSMHiggs Production:JQCD MatrixElement:JHUGen",
   "Name:JQCD_SIG_ghg2_1_JHUGen_JECUp Process:HSMHiggs Production:JQCD MatrixElement:JHUGen",
   "Name:JQCD_SIG_ghg2_1_JHUGen_JECDn Process:HSMHiggs Production:JQCD MatrixElement:JHUGen",
   #"Name:JQCD_SIG_ghg4_1_JHUGen Process:H0minus Production:JQCD MatrixElement:JHUGen",
   #"Name:JQCD_SIG_ghg4_1_JHUGen_JECUp Process:H0minus Production:JQCD MatrixElement:JHUGen",
   #"Name:JQCD_SIG_ghg4_1_JHUGen_JECDn Process:H0minus Production:JQCD MatrixElement:JHUGen",

   # ttH
   "Name:ttH_SIG_kappa_1_JHUGen Process:HSMHiggs Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappa_1_JHUGen_JECUp Process:HSMHiggs Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappa_1_JHUGen_JECDn Process:HSMHiggs Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappatilde_1_JHUGen Process:H0minus Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappatilde_1_JHUGen_JECUp Process:H0minus Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappatilde_1_JHUGen_JECDn Process:H0minus Production:ttH MatrixElement:JHUGen",
   "Name:ttH_SIG_kappa_1_tilde_1_JHUGen Process:SelfDefine_spin0 Production:ttH MatrixElement:JHUGen Couplings:kappa=1,0;kappa_tilde=1,0",
   "Name:ttH_SIG_kappa_1_tilde_1_JHUGen_JECUp Process:SelfDefine_spin0 Production:ttH MatrixElement:JHUGen Couplings:kappa=1,0;kappa_tilde=1,0",
   "Name:ttH_SIG_kappa_1_tilde_1_JHUGen_JECDn Process:SelfDefine_spin0 Production:ttH MatrixElement:JHUGen Couplings:kappa=1,0;kappa_tilde=1,0",

   # bbH
   "Name:bbH_SIG_kappa_1_JHUGen Process:HSMHiggs Production:bbH MatrixElement:JHUGen",
   "Name:bbH_SIG_kappa_1_JHUGen_JECUp Process:HSMHiggs Production:bbH MatrixElement:JHUGen",
   "Name:bbH_SIG_kappa_1_JHUGen_JECDn Process:HSMHiggs Production:bbH MatrixElement:JHUGen",

   # Leptonic ZH
   "Name:LepZH_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:Lep_ZH MatrixElement:JHUGen",

   "Name:LepZH_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_ghz2_1_JHUGen Process:H0hplus Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_ghz4_1_JHUGen Process:H0minus Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_gha2_1_JHUGen Process:H0_gsgs Production:Lep_ZH MatrixElement:JHUGen",
   "Name:LepZH_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:Lep_ZH MatrixElement:JHUGen",

   "Name:LepZH_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   "Name:LepZH_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   "Name:LepZH_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",

   "Name:LepZH_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   "Name:LepZH_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   "Name:LepZH_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   #"Name:LepZH_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",

   "Name:LepZH_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   #"Name:LepZH_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   "Name:LepZH_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   #"Name:LepZH_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_ZH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
   # Leptonic WH
   "Name:LepWH_SIG_ghz1_1_JHUGen Process:HSMHiggs Production:Lep_WH MatrixElement:JHUGen",

   "Name:LepWH_SIG_ghz1prime2_1_JHUGen Process:H0_g1prime2 Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_ghz2_1_JHUGen Process:H0hplus Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_ghz4_1_JHUGen Process:H0minus Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_ghza1prime2_1_JHUGen Process:H0_Zgsg1prime2 Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_ghza2_1_JHUGen Process:H0_Zgs Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_ghza4_1_JHUGen Process:H0_Zgs_PS Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_gha2_1_JHUGen Process:H0_gsgs Production:Lep_WH MatrixElement:JHUGen",
   "Name:LepWH_SIG_gha4_1_JHUGen Process:H0_gsgs_PS Production:Lep_WH MatrixElement:JHUGen",

   "Name:LepWH_SIG_ghz1_1_ghz1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghz1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz1_prime2=0,1",
   "Name:LepWH_SIG_ghz1_1_ghz2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghz2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz2=0,1",
   "Name:LepWH_SIG_ghz1_1_ghz4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghz4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghz4=0,1",

   "Name:LepWH_SIG_ghz1_1_ghza1prime2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghza1prime2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs1_prime2=0,1",
   "Name:LepWH_SIG_ghz1_1_ghza2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghza2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs2=0,1",
   "Name:LepWH_SIG_ghz1_1_ghza4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=1,0",
   #"Name:LepWH_SIG_ghz1_1_ghza4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghzgs4=0,1",

   "Name:LepWH_SIG_ghz1_1_gha2_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=1,0",
   #"Name:LepWH_SIG_ghz1_1_gha2_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs2=0,1",
   "Name:LepWH_SIG_ghz1_1_gha4_1_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=1,0",
   #"Name:LepWH_SIG_ghz1_1_gha4_1_pi2_JHUGen Process:SelfDefine_spin0 Production:Lep_WH MatrixElement:JHUGen Couplings:ghz1=1,0;ghgsgs4=0,1",
]

